<Hbox>:
	orientation:"horizontal"
	md_bg_color: app.theme_cls.primary_color


<Vbox>:
	orientation:"vertical"
	#md_bg_color: app.theme_cls.primary_color

<songitem@TwoLineAvatarIconListItem>:
	text:'no strategy yet'
	bg_color:0,0,0,1
	ImageLeftWidget:
		md_bg_color:0,0,0,1
		source:"alphaimg/music_item_icon.png"



<Card>:
	pos_hint: {'center_x': .5, 'center_y': .5}
	size_hint: None,None
	size: root.width-100,1000
	
	